language: ruby
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install: 
- rvm install 2.3.0-preview2 --create
- gem update bundler 
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false
