language: ruby
rvm:
- 2.3.0-preview2
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install:
- gem update bundler 
- rvm install ruby-2.3.0-preview2 --create
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false
