rvm:
- 2.6.2
language: ruby
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install:
- gem update --system
- gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
